accounts/api/urls.py
from email.mime import base
from django.urls import path, include 
 
from rest_framework.authtoken import views as token_views
from rest_framework.routers import DefaultRouter

from . import views     

app_name = 'accounts_api'

# router = DefaultRouter()
# router.register('users', views.CustomUserModelViewSets, basename='users')
 

urlpatterns = [  
    path('users/', views.CustomUserAPIView.as_view()),
    path('users/<int:pk>/', views.CustomUserAPIView.as_view()),
    path('users/my-details/', views.MyAccountView.as_view()),
    path('users/forget-password/', views.ForgetPasswordView.as_view()),
    path('users/forget-password/<token>/', views.ResetPasswordView.as_view(), name='reset-password' ),

    # path('get-my-token/', token_views.obtain_auth_token),
    path('login/', token_views.obtain_auth_token),
    path('users/add-certificate/', views.AddCertificateAPIView.as_view()),

] 
# + router.urls

accounts/urls.py
from django.urls import path 

from accounts.views import dashboard_views, views
 

app_name = 'accounts'

urlpatterns = [ 
    path('profile/', views.ProfileDetailView.as_view(), name='profile'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('forget-password/', views.ForgotPasswordView.as_view(), name='forget-password' ),
    path('reset-password/<token>/', views.ResetPasswordView.as_view(), name='reset-password'),
    path('update-profile/<int:pk>/', views.UserUpdateView.as_view(), name='update-profile'),

    #payment
    path('verify-payment/', views.VerifyPaymentView.as_view(), name='verify-payment'),

    path('my-certificate/', views.MyCertificateView.as_view(), name='my_certificate'),
    path('add-owner-certificate/', views.AddCertificateView.as_view(), name='add_owner_certificate'),

    path('my-reservations/', views.MyReservationsView.as_view(), name='reservations'),
    path('<int:pk>/my-reservation-details/', views.ReservationDetailView.as_view(), name='reservation_details'),
    path('<int:pk>/cancel-reservation/', views.CancelReservationView.as_view(), name='reservation_cancel'),
    
    path('myhotel/my-hotel-detail/', views.MyHotelDetailView.as_view(), name='my_hotel_detail'),
    path('myhotel/reservation-dashboard/', views.HotelReservationDashboardView.as_view(), name='myhotel_reservation'),
    path('myhotel/filter-reservations/', views.ReservationFilterByOwnerView.as_view(), name='myhotel_filter_reservations'),
    path('myhotel/<int:pk>/customer-reservation-detail/', views.CustomerReservationDetailView.as_view(), name='customer_reservation_detail'),
    path('myhotel/<int:pk>/update-customer-reservation/', views.UpdateCustomerReservationView.as_view(), name='update_customer_reservation'),

    path('dashboard/', dashboard_views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/group-filter/', dashboard_views.GroupUserFilterView.as_view(), name='group_filter'),
    path('dashboard/all-reservations/', dashboard_views.AllReservationView.as_view(), name='all_reservations' ),
    path('dashboard/reservation-hotel-filter/', dashboard_views.ReservationHotelFilterView.as_view(), name='reservation_hotel_filter'),
    path('dashboard/all-hotels/', dashboard_views.AllHotelsView.as_view(), name='all_hotels'),
    path('dashboard/<int:pk>/user-detail/', dashboard_views.DashboardUserDetail.as_view(), name='dashboard_user_detail'),
    path('dashboard/<int:pk>/verify-account/', dashboard_views.VerifyOwnerAccountView.as_view(), name='verify_account'),  

]

hbmsProject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('hotels.urls', namespace='hotels')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('stats/', include('stats.urls', namespace='stats')),

    path('api/hotels/', include('hotels.api.urls', namespace='hotels-api')),
    path('api/accounts/', include('accounts.api.urls', namespace='accounts-api')),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns +=  path('__debug__/', include('debug_toolbar.urls')), 
 

hotels/urls.py
from django.urls import path 

from . import views 

app_name = 'hotels'

urlpatterns = [ 
    path('', views.HotelListView.as_view(), name='hotel_list'),
    path('sort-hotel/', views.HotelSortView.as_view(), name='hotel_sort' ),
    # path('address/', views.HotelAddressSelectView.as_view(), name='hotel_address' ), 
    path('search/', views.HotelSearchView.as_view(), name='hotel_search'),

    path('add-hotel/', views.HotelCreateView.as_view(), name='hotel_create'),
    path('<int:pk>/detail/', views.HotelDetailView.as_view(), name='hotel_detail'),
    path('<int:pk>/update/', views.HotelUpdateView.as_view(), name='hotel_update'),
    path('<int:pk>/delete/', views.HotelDeleteView.as_view(), name='hotel_delete'),
    path('<int:pk>/comment/', views.HotelCommentView.as_view(), name='hotel_comment'),
    
    path('<int:pk>/reserve/', views.ReserveHotelView.as_view(), name='hotel_reserve'),
    

]

stats/urls.py
from django.urls import path 

from stats import views 

app_name = 'stats'

urlpatterns = [ 
    path('', views.HotelOwnerReportView.as_view(), name='report'),
    path('dashboard/reservation-report/', views.DashboardReservationReportView.as_view(), name='dashboard_reservation_report'),

    path('report/one-day-reservation/', views.pdfReportReservation, name='one_day_reservation_report'),
    path('report/reservation-date-pdf/', views.PdfReportReservationView2.as_view(), name='reservation_date_pdf'),
    

]

hotels/models.py
 
from django.db import models
from django.conf import settings
from django.urls import reverse 

# from accounts.models import CustomUser

# Create your models here.

class Hotel(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=10, null=True)
    email = models.CharField(max_length=200, null=True, unique=True)
    total_rooms = models.PositiveIntegerField(default=0)
    available_rooms = models.PositiveIntegerField(default=0)
    room_price = models.PositiveIntegerField(default=0)
    rate = models.PositiveIntegerField(default = 0)
    established = models.DateField()
    description = models.TextField(null=True, blank=True)
    # map_link = models.URLField(max_length=200, null=True, blank=True)
    map_link = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):  
        return reverse('hotels:hotel_detail', kwargs={'pk': self.pk})


class ImageModel(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='hotel_images')
    image = models.ImageField(upload_to='hotel', null=True, blank=True)

PAYMENT_METHOD = (
    ('online_pay', 'Online Pay'),
    ('offline_pay', 'Offline Pay')
)

"""RESERVATION_STATUS = (
    ('pending', 'pending'),
    ('completed', 'completed')
)"""

RESERVATION_STATUS = (
    ('reserved', 'reserved'),
    ('checked_in', 'checked_in'),
    ('checked_out', 'checked_out')
)

class Reservation(models.Model):
    no_of_rooms = models.PositiveIntegerField(default=0)
    reserved_date = models.DateTimeField(auto_now_add = True)
    checkin_date = models.DateTimeField(blank=True, null=True)
    checkout_date = models.DateTimeField(blank=True, null=True)
    amount = models.PositiveIntegerField(default=0)
    paid = models.BooleanField(default=False)
    payment_method = models.CharField(max_length=15, choices=PAYMENT_METHOD, default='offline_pay')
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='customer_reservations')
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='hotel_reservations')
    phone = models.CharField(max_length=10)   
    checkin_status =  models.CharField(max_length=15, choices=RESERVATION_STATUS, default="reserved")

    @property
    def get_CustomerName(self):
        return self.customer.username 

    @property
    def get_HotelName(self):
        return self.hotel.name

class Comment(models.Model):
    content = models.CharField(max_length=250, blank=False, null=False)
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='hotel_comments')
    date_time = models.DateTimeField(auto_now_add=True)

accounts/api/views.py
# from django.http import JsonResponse 
from hashlib import new
from django.db import IntegrityError
from django.http import JsonResponse 
from rest_framework.response import Response 
from rest_framework import viewsets, status
from rest_framework.views import APIView
# from rest_framework.authtoken.models import Token
# from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.permissions import IsAuthenticated 
from rest_framework.parsers import FormParser, MultiPartParser 

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.core.mail import send_mail 
from django.contrib.sites.shortcuts import get_current_site 
from django.conf import settings
from django.urls import reverse 

import uuid

from .serializer import (
    PasswordResetSerializer,
    UserSerializer,
    UserRetrieveUpdateSerializer, 
    NormalUpdateSerializer, 
    CertificateSerializer,
    ForgetPasswordSerializer
)
from .permissions import HotelOwnerMemberOnly
from accounts.models import Certificate

CustomUser = get_user_model()

# class CustomUserModelViewSets(viewsets.ModelViewSet):
#     serializer_class = UserSerializer
#     queryset = CustomUser.objects.all()
#     permission_classes = [IsAuthenticated]


class CustomUserAPIView(APIView):

    def get(self, request, pk=None, format=None):
        param_data = request.query_params  
        # print( Group.objects.get(name__iexact='customer-gang').user_set.all() )a
        id = pk 
        if id is not None: 
            if id==self.request.user.id or request.user.groups.filter(name__in=['admin-gang']).exists(): 
                user_obj = get_object_or_404(CustomUser, id=id)
                serializer = UserRetrieveUpdateSerializer(user_obj)
                return Response(serializer.data, status=status.HTTP_200_OK)
            return Response({"message": "Your're not allowed to view other user's data."}, status=status.HTTP_403_FORBIDDEN)

        elif request.user.groups.filter(name__in=['admin-gang']).exists():
            if param_data:
                try:
                    group_filter = param_data.get('group').strip()
                    if group_filter: 
                        users = Group.objects.get(name__iexact=group_filter).user_set.all().order_by('-id')
                    else:
                        users = CustomUser.objects.select_related('certificate').all().order_by('-id')
                except Exception as e:
                    return Response({"error": e.__str__(), "message": f"{group_filter} group doesn't exist"}, status=status.HTTP_400_BAD_REQUEST)
            else:
                users = CustomUser.objects.select_related('certificate').all().order_by('-id')
            
            serializers = UserRetrieveUpdateSerializer(users, many=True)
            return Response({"message":"Users data fetched successfully","count": len(users), "data": serializers.data}, status=status.HTTP_200_OK)
        
        return Response({'message': 'Not allowed'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

    def post(self, request, format=None): 
        if request.user.is_authenticated:
            return Response({'message': 'You need to be logged out before creating new user account.'})
        else:
            serializer = UserSerializer(data=request.data)
            if serializer.is_valid(): 
                serializer.save()
                # user = CustomUser.objects.get(username = serializer.data['username'])
                    # token_obj, _= Token.objects.get_or_create(user = user) 
                # return Response({'token': str(token_obj)}, status=200)
                return Response({'message': 'Account is created successfully'}, status=200)
            return Response({'errors': serializer.errors}, status=403)
    

    def put(self, request,pk, format=None):  

        obj = get_object_or_404(CustomUser,id = pk)
        if request.user.groups.filter(name__in=['admin-gang']).exists():
            serialized = UserRetrieveUpdateSerializer(instance=obj, data=request.data, partial=True)
            if serialized.is_valid():
                serialized.save()
                return Response({'message': 'update success', 'updated_data': serialized.data}, status=status.HTTP_200_OK)
            return Response({'errors': serialized.errors}, status=status.HTTP_400_BAD_REQUEST)
        else:
            if obj == request.user:
                serialized = NormalUpdateSerializer(instance=obj, data=request.data, partial=True)
                if serialized.is_valid():
                    serialized.save()
                    return Response({'message': 'udpate success', 'updated_data': serialized.data}, status=status.HTTP_200_OK)
                return Response({'errors': serialized.errors}, status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response({'message': "Sorry, you're not allowed to perform this action."}, status=status.HTTP_401_UNAUTHORIZED)

""" Password Reset """
def send_password_reset_mail(email,protocol, domain, token):
    link = protocol+"://"+ domain + reverse('accounts_api:reset-password', kwargs={'token': token})
    print(link)
    subject = "Your password reset link of YOYO's account" 
    message = f"Hello sir/maa'm, click on the link to reset your password {link}"
    
    send_mail(
        subject,
        message,
        settings.EMAIL_HOST_USER,
        [email,],
        fail_silently=False,
    )

class ForgetPasswordView(APIView):

    def post(self, request, format=None):
        serialized = ForgetPasswordSerializer(data=request.data)
        if serialized.is_valid():
            email = serialized.validated_data.get('email')
            user = CustomUser.objects.filter(email__iexact=email)
            if user.exists():
                user_obj = user.first()
                token = str(uuid.uuid4())
                user_obj.forget_password_token = token 
                user_obj.save()
                current_site = get_current_site(request)
                domain = current_site.domain
                protocol = "http"
                send_password_reset_mail(user_obj.email, protocol, domain, token)
                return JsonResponse({'message': 'Password reset link is sent through mail. Check your password reset mail.'}, status=status.HTTP_200_OK)
            else:
                return JsonResponse({'message': 'User does not exist with this email.'})
        return JsonResponse({'errors': serialized.errors}, status=status.HTTP_400_BAD_REQUEST)        


class ResetPasswordView(APIView):

    def post(self, request, token, format=None):
        user = CustomUser.objects.filter(forget_password_token = token).first()
        print(token)
        print(user)
        if user:
            serialized = PasswordResetSerializer(data = request.data)
            if serialized.is_valid():
                new_password = serialized.validated_data.get('password') 
                user.set_password(new_password)
                user.forget_password_token = None 
                user.save()  
                return JsonResponse({'message': 'Password reset success'}, status=status.HTTP_200_OK)
                
            return JsonResponse({'errors': serialized.errors}, status=status.HTTP_400_BAD_REQUEST)
        else:
            return JsonResponse({'error': 'Invalid token'}, status=status.HTTP_401_UNAUTHORIZED)

class MyAccountView(APIView):
    permission_classes = [IsAuthenticated, ]

    def get(self, request, format=None):
        serialized = UserRetrieveUpdateSerializer(request.user) 
        return Response({'data': serialized.data}, status = status.HTTP_200_OK)


class AddCertificateAPIView(APIView):
    permission_classes = [IsAuthenticated, HotelOwnerMemberOnly,]
    parser_classes = [FormParser, MultiPartParser]

    def post(self, request, *args, **kwargs): 
        # print(request.data.pop('image'))
        serialized = CertificateSerializer(data=request.data, context={'request': request}) 

        # print(request.data, serialized.is_valid())
        if serialized.is_valid(): 
            pass  
            
            ''' method 1 '''
            # obj = Certificate(user=request.user,image=request.data.get('image') ) 
            # obj.save()

            ''' method 2'''
            # serialized.save(user = request.user)
    
            try:
                ''' method 3'''
                serialized.save()
            except IntegrityError as e:
                # print(e.__str__()) 
                return Response({'message': 'You have already uploaded certificate','error': e.__str__()}, status=status.HTTP_403_FORBIDDEN )
            return Response({'message' : 'Certificate added successfully', 'data': serialized.data}, status=status.HTTP_201_CREATED)
        return Response({'errors': serialized.errors}, status=status.HTTP_400_BAD_REQUEST )

templates/accounts/owner/addOwnerCertificate.html
<form method="post" id="ownerCertificateFormId" novalidate>
    <div class="modal-header"> 
        <p style="font-family: 'Brush Script MT', cursive; font-size:26px; display: inline; " >Add Owner Certificate</p>
    </div>  
    {% csrf_token %}
    
    <div class="modal-body">
    {% for f in form %}
        <div class="mb-3">
            {{f.label_tag}} {{f}} <p><small class='text-muted'>{{f.help_text}}</small></p>
        </div>
    {% endfor %}
    </div>

    <div class="modal-footer">
        <input type="submit" class="btn btn-success" value="Upload Certificate">
        <button type="button" onclick="closeModal()" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
</form>

templates/accounts/owner/customerReservedDetail.html
<div class="modal-header"> 
    <p style="font-family: 'Brush Script MT', cursive; font-size:26px; display: inline; " >Customer Reservation Detail</p>
</div>   

<div class="modal-body"> 

    <table class="table table-striped">
        <tbody>
            <tr>
                <th scope="row">Hotel Name</th>
                <td>{{reservation.hotel}}</td>
            </tr>
            <tr>
                <th scope="row">No. of rooms</th>
                <td>{{reservation.no_of_rooms}}</td>
            </tr>
            <tr>
                <th scope="row">Reserved Date</th>
                <td>{{reservation.reserved_date}}</td>
            </tr>
            <tr>
                <th scope="row">Total Amount</th>
                <td>NPR{{reservation.amount}}</td>
            </tr>
            <tr>
                <th scope="row">Phone</th>
                <td>{{reservation.phone}}</td>
            </tr>
            <tr>
                <th scope="row">Checkin-Date</th>
                <td>
                    {% if reservation.checkin_date %}
                        {{reservation.checkin_date}}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th scope="row">Checkout-Date</th>
                <td>
                    {% if reservation.checkout_date %}
                        {{reservation.checkout_date}}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th scope="row">Payment method</th>
                <td>{{reservation.payment_method}}</td>
            </tr>
            <tr>
                <th scope="row">Paid</th>
                <td>
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" disabled {% if reservation.paid %}checked{% endif %}>
                </td>
            </tr>   
            <tr>
                <th scope="row">Checkin-Status</th>
                <td>
                    <small class='badge bg-{% if reservation.checkin_status == "reserved" %}warning text-dark{% elif reservation.checkin_status == "checked_in" %}info text-dark{% else %}success{% endif %}'>{{reservation.checkin_status}}</small>
                </td>
            </tr>

            {% if reservation.checkin_status == "reserved" %}
            <tr>
                <th scope="row">Cancel Booking</th>
                <td> 
                    <form method="post" id="cancelBookingId" data-reservationId="{{reservation.id}}">
                        {% csrf_token %}
                        <input type="submit"  class="btn btn-danger" value="Cancel Booking" style="width: 100%;" />
                    </form>
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>

<div class="modal-footer">  
    {% if  reservation.checkin_status != "checked_out" or reservation.paid == False %}
        <a href="{% url 'accounts:update_customer_reservation' reservation.id %}" id="updateCustomerReservationId" class="btn btn-info" style="padding-left: 30px; padding-right: 30px;">Update Detail</a>
    {% endif %}
    <button type="button" onclick="closeModal()" class="btn btn-secondary" data-bs-dismiss="modal" style="padding-left: 30px; padding-right: 30px;">Close</button>
</div> 

templates/accounts/owner/myHotelDetail.html
{% load static %}
<div class="mx-auto" style="font-weight:normal; width: 100%;"> 

        {% with hotel=request.user.hotel %}
        <p style="font-family: 'Brush Script MT', cursive; font-size:35px;">My Hotel</p>
        <hr>
        <div class="col-sm-4 mt-4 mb-2" >
            <div class="card card-hover" id="card1" >
                {% with h=hotel.hotel_images.all %} 
                    <img src="{% if h.count > 0 %} {{h.first.image.url}} {% else %} {% static 'default_hotel.jpeg' %} {% endif %}" style="height: 280px; width:100%;" class="card-img-top" alt="...">
                {% endwith %}
                <div class="card-body">
                    <a href="{% url 'hotels:hotel_detail' hotel.owner.id %}" style="text-decoration: none;"><h5 class="card-title">{{hotel.name|truncatechars:18}}</h5></a>
                    <p class="card-text">{{ hotel.address|truncatechars:35 }}</p> 
                    <p class="alert alert-secondary">Per Room Price: <b>NPR{{hotel.room_price}}</b></p>
                </div>
            </div>
        </div> 
        {% endwith %} 

</div>

templates/accounts/owner/mycerfiticate.html
<p style="font-family: 'Brush Script MT', cursive; font-size:35px;">My Certificate</p>
<hr>
<img src="{{request.user.certificate.image.url}}" height="800px">

templates/accounts/owner/reservationFilteredData.html
{% for r in reservation_list %}
    <tr>
    <td>{{forloop.counter}}</td>
    <td>{{r.customer.username}}</td>
    <td>{{r.no_of_rooms}}</td> 
    <td>{{r.reserved_date}}</td> 
    <td>
        <small class='badge bg-{% if r.checkin_status == "reserved" %}warning text-dark{% elif r.checkin_status == "checked_in" %}info text-dark{% else %}success{% endif %}'>{{r.checkin_status}}</small>
    </td>
    <td>
        {% if r.paid %}
        <input class="form-check-input" type="checkbox" checked disabled>
        {% else %}
        <input class="form-check-input" type="checkbox" disabled>
        {% endif %}
    </td>
    <td>
        <a href="{% url 'accounts:customer_reservation_detail' r.id %}" class="btn btn-info" id="detailCustomerReservationId">Details</a>
    </td>
    
    </tr> 
{% endfor %}

templates/accounts/owner/updateReservedDetail.html
<form method="post" id="upateCustomerReservationFormId" data-reservationId="{{reservationId}}" novalidate >
    <div class="modal-header"> 
        <p style="font-family: 'Brush Script MT', cursive; font-size:26px; display: inline; " >Update Customer Reservation Detail</p>
    </div>  
    {% csrf_token %}
    
    <div class="modal-body">
    {% for f in form %}
        <div class="mb-3">
            {{f.label_tag}} {{f}}
        </div>
    {% endfor %}
    </div>

    <div class="modal-footer">
        <input type="submit" class="btn btn-success" value="Update">
        <button type="button" onclick="closeModal()" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
</form>