accounts/urls.py
from django.urls import path 

from accounts.views import dashboard_views, views
 

app_name = 'accounts'

urlpatterns = [ 
    path('profile/', views.ProfileDetailView.as_view(), name='profile'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('forget-password/', views.ForgotPasswordView.as_view(), name='forget-password' ),
    path('reset-password/<token>/', views.ResetPasswordView.as_view(), name='reset-password'),
    path('update-profile/<int:pk>/', views.UserUpdateView.as_view(), name='update-profile'),

    #payment
    path('verify-payment/', views.VerifyPaymentView.as_view(), name='verify-payment'),

    path('my-certificate/', views.MyCertificateView.as_view(), name='my_certificate'),
    path('add-owner-certificate/', views.AddCertificateView.as_view(), name='add_owner_certificate'),

    path('my-reservations/', views.MyReservationsView.as_view(), name='reservations'),
    path('<int:pk>/my-reservation-details/', views.ReservationDetailView.as_view(), name='reservation_details'),
    path('<int:pk>/cancel-reservation/', views.CancelReservationView.as_view(), name='reservation_cancel'),
    
    path('myhotel/my-hotel-detail/', views.MyHotelDetailView.as_view(), name='my_hotel_detail'),
    path('myhotel/reservation-dashboard/', views.HotelReservationDashboardView.as_view(), name='myhotel_reservation'),
    path('myhotel/filter-reservations/', views.ReservationFilterByOwnerView.as_view(), name='myhotel_filter_reservations'),
    path('myhotel/<int:pk>/customer-reservation-detail/', views.CustomerReservationDetailView.as_view(), name='customer_reservation_detail'),
    path('myhotel/<int:pk>/update-customer-reservation/', views.UpdateCustomerReservationView.as_view(), name='update_customer_reservation'),

    path('dashboard/', dashboard_views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/group-filter/', dashboard_views.GroupUserFilterView.as_view(), name='group_filter'),
    path('dashboard/all-reservations/', dashboard_views.AllReservationView.as_view(), name='all_reservations' ),
    path('dashboard/reservation-hotel-filter/', dashboard_views.ReservationHotelFilterView.as_view(), name='reservation_hotel_filter'),
    path('dashboard/all-hotels/', dashboard_views.AllHotelsView.as_view(), name='all_hotels'),
    path('dashboard/<int:pk>/user-detail/', dashboard_views.DashboardUserDetail.as_view(), name='dashboard_user_detail'),
    path('dashboard/<int:pk>/verify-account/', dashboard_views.VerifyOwnerAccountView.as_view(), name='verify_account'),  

]

hbmsProject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('hotels.urls', namespace='hotels')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('stats/', include('stats.urls', namespace='stats')),

    path('api/hotels/', include('hotels.api.urls', namespace='hotels-api')),
    path('api/accounts/', include('accounts.api.urls', namespace='accounts-api')),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns +=  path('__debug__/', include('debug_toolbar.urls')), 
 

hotels/urls.py
from django.urls import path 

from . import views 

app_name = 'hotels'

urlpatterns = [ 
    path('', views.HotelListView.as_view(), name='hotel_list'),
    path('sort-hotel/', views.HotelSortView.as_view(), name='hotel_sort' ),
    # path('address/', views.HotelAddressSelectView.as_view(), name='hotel_address' ), 
    path('search/', views.HotelSearchView.as_view(), name='hotel_search'),

    path('add-hotel/', views.HotelCreateView.as_view(), name='hotel_create'),
    path('<int:pk>/detail/', views.HotelDetailView.as_view(), name='hotel_detail'),
    path('<int:pk>/update/', views.HotelUpdateView.as_view(), name='hotel_update'),
    path('<int:pk>/delete/', views.HotelDeleteView.as_view(), name='hotel_delete'),
    path('<int:pk>/comment/', views.HotelCommentView.as_view(), name='hotel_comment'),
    
    path('<int:pk>/reserve/', views.ReserveHotelView.as_view(), name='hotel_reserve'),
    

]

stats/urls.py
from django.urls import path 

from stats import views 

app_name = 'stats'

urlpatterns = [ 
    path('', views.HotelOwnerReportView.as_view(), name='report'),
    path('dashboard/reservation-report/', views.DashboardReservationReportView.as_view(), name='dashboard_reservation_report'),

    path('report/one-day-reservation/', views.pdfReportReservation, name='one_day_reservation_report'),
    path('report/reservation-date-pdf/', views.PdfReportReservationView2.as_view(), name='reservation_date_pdf'),
    

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
   
    <script src="{% static 'js/jquery-3.6.0.min.js' %}" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script> -->
    <script src="{% static 'js/chart.js' %}"></script>
    <script src="{% static 'js/khalti-checkout.iffe.js' %}"></script>

    <title>YOYO {% block title %}{% endblock %}</title>
    <style>
        .card-hover:hover{
            transform: scale(1.09);
        }
    {% block css %}

    {% endblock %}
    </style>
    {% block links %} {% endblock %}
</head>
<body>
    {% include 'header.html' %}

    <div class="container-fluid" style="padding-left:88px; padding-right: 88px;">
        {% block content %}{% endblock %}
    </div>
 
</body>
</html>

templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light " style="padding-left:75px; padding-right: 75px;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'hotels:hotel_list' %}" style="font-size:25px ;">YOYO</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'hotels:hotel_list' %}"> Home </a>
          </li>  
          {% if is_adminMember %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:dashboard' %}">Dashboard</a>
            </li> 
          {% endif %}

          {% if is_hotelOwnerMember %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:myhotel_reservation' %}">Reservations</a>
            </li> 
          {% endif %}
          <!-- <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'stats:report' %}">Report</a>
          </li>  -->

        </ul>
        <!-- <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->

        <div class="d-flex" >
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}" style=" text-decoration: none;" class=" position-relative"> 
                <img style="height: 30px; width: 30px; border-radius: 20px;" src="{% static 'default_image.jpg' %}" alt="">
                <b>{{request.user.username}}</b>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" style="margin-left: 5px;">
                  {{my_reservationCount}} 
                </span>
            </a>
            <a href="{% url 'accounts:logout' %}" style="margin-left: 25px; text-decoration: none;color:black;">Logout</a>
        {% else %} 
            <a class="nav-link" href="{% url 'accounts:signup' %}" style="color:black;">Signup</a> 
            <a class="nav-link" href="{% url 'accounts:login' %}" style="color:black;">Login</a>
        {% endif %}
        </div>
      </div>
    </div>
  </nav>